# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_orgao', models.IntegerField()),
                ('descricao', models.CharField(max_length=100, verbose_name='Descri\xe7\xe3o')),
                ('sigla', models.CharField(max_length=20, verbose_name='SIGLA')),
                ('site', models.EmailField(default='info@orgao.co.ao', max_length=254, verbose_name='E-mail')),
                ('estado', models.BooleanField(default=True, verbose_name='Activado')),
                ('data_registo', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
