# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20180223_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_servico', models.IntegerField(unique=True, verbose_name='C\xf3digo')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descri\xe7\xe3o')),
                ('estado', models.BooleanField(default=True, verbose_name='Activado')),
                ('data_registo', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='webapi.categoria'),
        ),
        migrations.AlterField(
            model_name='posto',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgao', to='webapi.orgao'),
        ),
        migrations.AddField(
            model_name='servico',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posto', to='webapi.posto'),
        ),
    ]
