# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20180223_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='posto',
        ),
        migrations.AddField(
            model_name='posto',
            name='servicos',
            field=models.ManyToManyField(to='webapi.servico'),
        ),
    ]
