# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20180226_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Cat\xe9goria'},
        ),
        migrations.AlterModelOptions(
            name='orgao',
            options={'verbose_name': 'Org\xe3o'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Servi\xe7o'},
        ),
    ]
