# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_agente_utilizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda-feira', 'SEGUNDA-FEIRA'), ('ter\xe7a-feira', 'TER\xc7A-FEIRA'), ('quarta-feira', 'QUARTA-FEIRA'), ('quinta-feira', 'QUINTA-FEIRA'), ('sexta-feira', 'SEXTA-FEIRA')], max_length=20)),
                ('horainicio', models.TimeField(help_text='Hora de \xcdnicio', verbose_name='Hora de \xcdnicio')),
                ('horafinal', models.TimeField(help_text='Hora de \xcdnicio', verbose_name='Hora de \xcdnicio')),
            ],
            options={
                'verbose_name': 'Hor\xe1rio',
            },
        ),
        migrations.AddField(
            model_name='posto',
            name='horarios',
            field=models.ManyToManyField(to='webapi.horario'),
        ),
    ]
